## Arrays & Data frames - NumPy tutorial
### Import NumPy

In [4]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## NumPy as np

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### NumPy Creating Arrays
### Create a NumPy ndarray Object

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method

In [14]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


## Dimensions in Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [24]:
import numpy as np

arr = np.array(4)

print(arr)

4


1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

In [37]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [40]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]



Check Number of Dimensions using ndim

In [43]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays define the number of dimensions by using the ndmin

In [46]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


Array Indexing
Access Array Elements

You can access an array element by referring to its index number.

In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])

#Get third and fourth elements from the following array and add them.
print(arr[2] + arr[3])

1
2
7


Access 2-D Arrays

In [52]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('2nd element on 2st row: ', arr[1, 1])

2nd element on 1st row:  2
2nd element on 2st row:  7


Access 3-D Arrays

In [55]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr )
print(arr[0, 1, 1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
5


Negative Indexing

In [58]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('  element from 2nd dim: ', arr[1, -1])
print('  element from 1nd dim: ', arr[0, -2])

  element from 2nd dim:  10
  element from 1nd dim:  4


## NumPy Array Slicing

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[2:5])
print(arr[3:6])
print(arr[3:7])

[2 3 4 5]
[3 4 5]
[4 5 6]
[4 5 6 7]


In [64]:
#Slice elements from index 3 to the end of the array:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[3:])

[4 5 6 7]


In [66]:
#Slice elements from the beginning to index 3 (not included):
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:3])

[1 2 3]


## Negative Slicing

In [69]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-4:-1])

[4 5 6]


## NumPy Array Shape

The shape of an array is the number of elements in each dimension.

In [75]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [77]:
#Create an array with 4 dimensions using ndmin using a vector with values 1,2,3,4  
# and verify that last dimension has value 4:

import numpy as np

arr = np.array([1, 2, 3, 4 ], ndmin=4)

print(arr)
print('shape of array :', arr.shape)

[[[[1 2 3 4]]]]
shape of array : (1, 1, 1, 4)


## Array Reshaping

Reshape From 1-D to 2-D

In [82]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
newarr1 = arr.reshape(3, 4)
newarr2 = arr.reshape(2, 6)

print(newarr)
print(newarr1)
print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Reshape From 1-D to 3-D

In [85]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
newarr1 = arr.reshape(3, 2, 2)
newarr2 = arr.reshape(2, 2, 3)

print(newarr)
print("------")
print(newarr1)
print("------")
print(newarr2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
------
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Python NumPy Array Creation - Empty, Zeroes and Ones

In [88]:
#Using numpy.empty Basic Example:
#create an empty array. Also, elements in an array will show random values because 
# they are not initialized:

import numpy as np 

# an array with 4 rows and 3 columns
x = np.empty([4,3], dtype = int) 
print (x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [90]:
#Using numpy.zeroes Basic Example:
#The below code example will create an array of dimension 3x3 with all elements initialized as 0.
import numpy as np  

arr = np.zeros((3,3), dtype = int)  
print(arr)  

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [92]:
#Using numpy.ones Basic Example: 
import numpy as np  

arr = np.ones((3,3), dtype = int)  
print(arr)  

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## Joining Array

In [97]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [99]:
#Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
arr1 = np.concatenate((arr1, arr2), axis=1)
print(arr)
print("-------------------")
print(arr1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-------------------
[[1 2 5 6]
 [3 4 7 8]]


## Splitting Array

In [102]:
#Split the array in 3 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


## Splitting 2-D Arrays 

In [107]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [109]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


## Searching Arrays

In [112]:
#Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) # the value 4 is present at index 3, 5, and 6.

(array([3, 5, 6], dtype=int64),)


In [114]:
#Find the indexes where the values are odd:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)
